# Generated by Django 3.2.8 on 2021-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('inInventory', models.BooleanField(default=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('depositDate', models.DateTimeField()),
                ('withDate', models.DateTimeField(default=None)),
            ],
        ),
    ]
