# Generated by Django 3.2.8 on 2021-10-29 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_botitems_items_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='codeRedeemed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='lastLogDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='regDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='totalUSDLoses',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='totalUSDProfit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='totalUSDWin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='lang',
            field=models.CharField(default='eng', max_length=20),
        ),
    ]
